### ISSUE TITLE
Task1

### ISSUE THREAD

**Issue by YakutovDmitriy** [assrichiacoli/hw#1]
Please implement all functions in file `task.py`.

Thanks,
Dmitry

**Comment by assrichiacoli** [comment]
done

**Comment by YakutovDmitriy** [comment]
`frequencyDict` is ok, but other implementations has some issues. Please test them using tests from here: `https://github.com/YakutovDmitriy/bio-python-course-2018/tree/master/task1`. Also you should return the result from function, not print it

**Comment by assrichiacoli** [comment]
ok! I have tested them though🤔

**Comment by assrichiacoli** [comment]
done!

**Comment by YakutovDmitriy** [comment]
Functions `unique` and `transposeDict` are ok now :+1: 
But you still have a problem with `mex`. Sample tests are ok, but it is possible to create list `e` such that you have an error [https://github.com/assrichiacoli/hw/blob/master/task1.py#L24](here).
It is possible to make this task without `try-except` clause. Moreover, it is possible to delete some piece of your code to get correct solution. :smirk:

**Comment by assrichiacoli** [comment]
Done I believe))

The link doesn't work. What list gave an error in my previous code? I can't think of one...

**Comment by YakutovDmitriy** [comment]
Now it is ok!

The link doesn't work because you pushed new commit to master, I guess.
There was an error in expression `int(i)`. You catched `ValueError`, but there are other exception types raises sometimes, e.g `TypeError` when `i = None`.

**Comment by assrichiacoli** [comment]
in what cases can i be None?🤔

**Comment by YakutovDmitriy** [comment]
Foe example when `e = [None, 1, 2, 3]`. :small_airplane:

**Comment by assrichiacoli** [comment]
ohh ok thanks
